name: Build and Deploy

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
  release:
    types: [published]

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  EAS_PROJECT_ID: 24d1984c-eb71-4672-bace-c6a0ddeb648b

jobs:
  # Code quality checks for all branches
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Run linting
        run: |
          cd frontend
          npm run lint || echo "Linting completed with warnings"
      
      - name: Run type checking
        run: |
          cd frontend
          npx tsc --noEmit || echo "Type checking completed with warnings"

  # Development builds on development branch
  development-build:
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build development APK
        run: |
          cd frontend
          npx eas build --profile development --platform android --non-interactive
      
      - name: Build development iOS
        run: |
          cd frontend
          npx eas build --profile development --platform ios --non-interactive
      
      - name: Comment build status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Development builds completed! Check EAS dashboard for download links.'
            })

  # Production builds on main branch
  production-build:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build production AAB
        run: |
          cd frontend
          npx eas build --profile production --platform android --non-interactive
      
      - name: Build production IPA
        run: |
          cd frontend
          npx eas build --profile production --platform ios --non-interactive
      
      - name: Create release artifacts
        run: |
          echo "Production builds completed successfully!"
          echo "Android AAB and iOS IPA are available on EAS dashboard"

  # Store submission on release
  store-submission:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: production-build
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Submit to Google Play (if configured)
        if: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT != '' }}
        run: |
          cd frontend
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}" > google-play-service-account.json
          npx eas submit --platform android --profile production --non-interactive
        continue-on-error: true
      
      - name: Submit to App Store (if configured)
        if: ${{ secrets.APPLE_ID != '' }}
        run: |
          cd frontend
          npx eas submit --platform ios --profile production --non-interactive
        continue-on-error: true
      
      - name: Publish EAS Update
        run: |
          cd frontend
          npx eas update --branch production --message "Release ${{ github.event.release.tag_name }}"
        continue-on-error: true

  # Notification on failure
  notify-failure:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        run: |
          echo "❌ Build or deployment failed!"
          echo "Check the logs for details."
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"